# Generated by Django 4.0.4 on 2022-08-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpanishVocabularyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word_macedonian',
            new_name='macedonian',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word_spanish',
            new_name='spanish',
        ),
    ]
