# Generated by Django 4.0.4 on 2022-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpanishVocabularyApp', '0002_rename_category_image_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
