# Generated by Django 4.0.4 on 2022-08-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpanishVocabularyApp', '0003_category_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
